engines:
  duplication:
    enabled: true
    exclude_fingerprints:
    # ignore BarChart calc_min calc_max code duplication:
    - 7da5b03898f765e54ffb90813cf0865b
    config:
      languages:
        ruby:
ratings:
  paths:
  - lib/**
  - "**.rb"
exclude_paths:
- spec/**/*
