engines:
  duplication:
    enabled: true
    exclude_fingerprints:
    # ignore BarChart calc_min calc_max code duplication:
    - da0fcfc0732d98fcffb520452bee824a
    config:
      languages:
        ruby:
ratings:
  paths:
  - lib/**
  - "**.rb"
exclude_paths:
- spec/**/*
